import { Schema, model, Document } from 'mongoose';

interface IItem extends Document {
    name: string,
    slot: string,
    rarity: string,
    owned: number,
    stats: {
    attack: number,
    charisma: number,
    intelligence: number,
    dexterity: number,
    luck: number,
    }
    makeItem: Function,
}

interface IPrefix {
    name: string,
    attack: number,
    charisma: number,
    intelligence: number,
    dexterity: number,
    luck: number,
}

interface ISuffix{
    name: string,
    attack: number,
    charisma: number,
    intelligence: number,
    dexterity: number,
    luck: number,
    the: boolean,
}

interface IEquip{
    name: string,
    attack: number,
    charisma: number,
    intelligence: number,
    dexterity: number,
    luck: number,
    slot: string,
}

const ItemSchema = new Schema({
    name: String,
    slot: String,
    rarity: {
        type: String,
        enum: ['normal', 'rare', 'epic', 'legendary', 'ascended', 'sets'],
    },
    owned: {
        type: Number,
        default: 0,
        min: 0,
    },
    stats: {
        attack: {
            type: Number,
            default: 0,
            min: -100,
        },
        intelligence: {
            type: Number,
            default: 0,
            min: -100,
        },
        charisma: {
            type: Number,
            default: 0,
            min: -100,
        },
        dexterity: {
            type: Number,
            default: 0,
            min: -100,
        },
        luck: {
            type: Number,
            default: 0,
            min: -100,
        },
    },
});

ItemSchema.methods.makeItem = function ()
{


const prefixes: Array<IPrefix> = [
    {
    name: 'Fine',
    attack: 1,
    charisma: 1,
    dexterity: 1,
    intelligence: 1,
    luck: 1
    },
    {
    name: 'Firm', 
    attack: 2,
    charisma: 0,
    intelligence: 2,
    dexterity: 0,
    luck: 0
    },
    {
    name: 'Patched',
    attack: -1,
    dexterity: 1,
    intelligence: -1,
    luck: 2,
    charisma: 0
    },
    {
    name:'Reforged', 
      attack: 1,
      charisma: 1,
      intelligence: 0,
      dexterity: 0,
      luck: 0,
    },
    {
    name:'Rugged', 
      attack: 2,
      charisma: 2,
      intelligence: 2,
      dexterity: 0,
      luck: 0,
    },
    {
    name:'Savage', 
      attack: 3,
      charisma: -2,
      intelligence: 3,
      dexterity: 0,
      luck: 0,
    },
    {
    name:'Scarred', 
      attack: -2,
      charisma: -2,
      intelligence: -2,
      luck: -2,
      dexterity: 0,
    },
    {
    name: 'Sinister', 
      attack: 4,
      charisma: -2,
      intelligence: -2,
      dexterity: 0,
      luck: 0,
    },
    {
    name:'Tiny', 
      attack: -2,
      charisma: 1,
      dexterity: 2,
      intelligence: -2,
      luck: 0,
    },
    {
    name:'Unholy', 
      charisma: -2,
      intelligence: 3,
      luck: -3,
      attack: 0,
      dexterity: 0,
    },
    {
    name:'Zealous', 
      attack: 2,
      charisma: 2,
      dexterity: 1,
      luck: 0,
      intelligence: 0,
    },
    {
    name:'Cursed', 
      attack: 5,
      charisma: -2,
      dexterity: -3,
      luck: -50,
      intelligence: 0,
    },
    {
    name:'Encharismanted',
      attack: 5,
      charisma: 3,
      dexterity: 5,
      intelligence: 0,
      luck: 0,
    },
    {
    name:'Shiny',
    attack: 0,
    intelligence: 0,
    charisma: 3,
    dexterity: 0,
    luck: 0,
    },
    {
    name:'Blessed',
      attack: 2,
      charisma: 4,
      dexterity: 1,
      intelligence: 8,
      luck: 12
    },
    {
    name:'Godly',
      attack: 8,
      charisma: 8,
      dexterity: 8,
      intelligence: 8,
      luck: 8
    },
    {
    name:'Ultimate',
      attack: 12,
      charisma: 12,
      dexterity: 12,
      intelligence: 12,
      luck: 12
    },
    {
    name:'Fancy',
    attack: 0,
    dexterity: 0,
    intelligence: 0, 
    charisma: 15,
    luck: 0,
    },
    {
    name:'Comfortable',
    attack: 0,
    charisma: 0, 
    dexterity: 15,
    intelligence: 0,
    luck: 0,
    },
    {
    name:'Barbaric',
    attack: 15,
    luck: 0,
    dexterity: 0,
    intelligence: 0,
    charisma: 0,
    },
    {
    name:'Strange', 
    intelligence: 15,
    attack: 0,
    charisma: 0,
    dexterity: 0,
    luck: 0,
    },
    {
    name:'Lucky',
    attack: 0,
    intelligence: 0,
    charisma: 0,
    dexterity: 0,
    luck: 15
    },
    {
    name:'Celestial', 
      attack: 5,
      charisma: 10,
      dexterity: 2,
      intelligence: 16,
      luck: 20
    },
    {
    name:'Demonic', 
      attack: 18,
      charisma: 10,
      dexterity: 2,
      intelligence: 5,
      luck: 10
    }
];

const suffixes: Array<ISuffix> = [

{
    name: 'Adventure', 
    attack: 3,
    charisma: 3,
    dexterity: 3,
    intelligence: 3,
    luck: 3,
    the: false,
  },
  {
    name: 'Clarity', 
    charisma: 2,
    dexterity: 2,
    intelligence: 3,
    luck: 1,
    the: false,
    attack: 0,
  },
  {
    name: 'Eternity', 
    attack: 2,
    intelligence: 4,
    luck: 2,
    the: false,
    charisma: 0,
    dexterity: 0,
  },
  {
    name: 'Extinction', 
    attack: 3,
    charisma: -2,
    intelligence: 3,
    the: false,
    luck: 0,
    dexterity: 0,
  },
  {
    name: 'Fools', 
    charisma: 2,
    the: false,
    attack: 0,
    intelligence: 0,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'Fury', 
    attack: 4,
    intelligence: 2,
    the: false,
    charisma: 0,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'Kings', 
    attack: 2,
    intelligence: 2,
    luck: 3,
    the: false,
    charisma: 0,
    dexterity: 0,
  },
  {
    name: 'Memories', 
    intelligence: 3,
    attack: 0,
    luck: 0,
    charisma: 0,
    dexterity: 0,
    the: false,
  },
  {
    name: 'Stealth', 
    dexterity: 4,
    luck: 2,
    the: false,
    attack: 0,
    charisma: 0,
    intelligence: 0,
  },
  {
    name: 'Suffering', 
    attack: 2,
    charisma: 1,
    intelligence: 2,
    dexterity: 2,
    the: false,
    luck: 0,
  },
  {
    name: 'Resilience', 
    attack: 3,
    charisma: 1,
    intelligence: 1,
    the: false,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'West', 
    the: true,
    attack: 0,
    charisma: 0,
    intelligence: 0,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'Supreme One', 
    the: true,
    attack: 15,
    charisma: 15,
    intelligence: 15,
    dexterity: 15,
    luck: 0,
  },
  {
    name: 'Destiny', 
    luck: 12,
    the: false,
    attack: 0,
    charisma: 0,
    intelligence: 0,
    dexterity: 0,
  },
  {
    name: 'Fate', 
    luck: 10,
    the: false,
    attack: 0,
    charisma: 0,
    intelligence: 0,
    dexterity: 0,
  },
  {
    name: 'charismampions', 
    attack: 12,
    the: false,
    charisma: 0,
    intelligence: 0,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'Conquerors', 
    attack: 10,
    charisma: -12,
    the: false,
    intelligence: 0,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'Wisdom',
    intelligence: 12,
    the: false,
    attack: 0,
    charisma: 0,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'Sage', 
    the: true,
    intelligence: 10,
    attack: 0,
    charisma: 0,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'Mind', 
    the: true,
    charisma: 12,
    attack: 0,
    luck: 0,
    intelligence: 0,
    dexterity: 0,
  },
  {
    name: 'Priest', 
    the: true,
    charisma: 10,
    attack: 0,
    intelligence: 0,
    dexterity: 0,
    luck: 0,
  },
  {
    name: 'Nimble', 
    the: true,
    dexterity: 12,
    attack: 0,
    charisma: 0,
    intelligence: 0,
    luck: 0,
  },
  {
    name: 'Thief', 
    the: true,
    dexterity: 10,
    attack: 0,
    charisma: 0,
    intelligence: 0,
    luck: 0,
  }
];

const equipment: Array<IEquip> = [
{
    name : 'Band',
    slot: 'belt', 
    dexterity: 1,
    intelligence: 1,
    charisma: 0,
    luck: 0,
    attack: 0,
},
{
    name : 'Belt',
    slot: 'belt', 
    dexterity: 1,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 1,
},
{
    name : 'Cord',
    slot: 'belt', 
    dexterity: 2,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 0,
},
{
    name : 'Strap',
    slot: 'belt', 
    dexterity: 0,
    intelligence: 2,
    charisma: 0,
    luck: 0,
    attack: 2,
},
{
    name : 'Waistband',
    slot: 'belt', 
    dexterity: 0,
    intelligence: 1,
    charisma: 0,
    luck: 0,
    attack: 1,
},
{
    name : 'Boots',
    slot: 'boots', 
    dexterity: -1,
    intelligence: 1,
    charisma: 0,
    luck: 0,
    attack: 1,
},
{
    name : 'Clogs',
    slot: 'boots', 
    dexterity: 0,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 0,
},
{
    name : 'Sabatons',
    slot: 'boots', 
    dexterity: -1,
    intelligence: 2,
    charisma: 2,
    luck: 0,
    attack: 2,
},
{
    name : 'Slip-Ons',
    slot: 'boots', 
    dexterity: 1,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 0,
},
{
    name : 'Stompers',
    slot: 'boots', 
    dexterity: 0,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 2,
},
{
    name : 'Amulet',
    slot: 'charismarm', 
    dexterity: 0,
    intelligence: 2,
    charisma: 1,
    luck: 1,
    attack: 1,
},
{
    name : 'charismarm',
    slot: 'charismarm', 
    dexterity: 0,
    intelligence: 1,
    charisma: 3,
    luck: 1,
    attack: 1,
},
{
    name : 'Medallion',
    slot: 'charismarm', 
    dexterity: 0,
    intelligence: 2,
    charisma: 1,
    luck: 0,
    attack: 2,
},
{
    name : 'Shard',
    slot: 'charismarm', 
    dexterity: 1,
    intelligence: 3,
    charisma: 0,
    luck: 2,
    attack: 3,
},
{
    name : 'Armor',
    slot: 'chest', 
    dexterity: 0,
    intelligence: 0,
    charisma: 1,
    luck: 0,
    attack: 1,
},
{
    name : 'Battackleplate',
    slot: 'chest', 
    dexterity: -2,
    intelligence: 2,
    charisma: 1,
    luck: 0,
    attack: 3,
},
{
    name : 'Chestplate',
    slot: 'chest', 
    dexterity: -1,
    intelligence: 2,
    charisma: 2,
    luck: 1,
    attack: 2,
},
{
    name : 'Robes',
    slot: 'chest', 
    dexterity: 2,
    intelligence: 2,
    charisma: 0,
    luck: 2,
    attack: 0,
},
{
    name : 'Vest',
    slot: 'chest', 
    dexterity: 3,
    intelligence: 1,
    charisma: 1,
    luck: 1,
    attack: 1,
},
{
    name : 'Fists',
    slot: 'gloves', 
    dexterity: 2,
    intelligence: -2,
    charisma: -1,
    luck: 0,
    attack: 2,
},
{
    name : 'Gauntlets',
    slot: 'gloves', 
    dexterity: -1,
    intelligence: 2,
    charisma: 1,
    luck: 0,
    attack: 2,
},
{
    name : 'Gloves',
    slot: 'gloves', 
    dexterity: 1,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 0,
},
{
    name : 'Grips',
    slot: 'gloves', 
    dexterity: 0,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 1,
},
{
    name : 'Crown',
    slot: 'head', 
    dexterity: 2,
    intelligence: 3,
    charisma: 3,
    luck: 2,
    attack: 1,
},
{
    name : 'Faceguard',
    slot: 'head', 
    dexterity: 2,
    intelligence: 0,
    charisma: 0,
    luck: 1,
    attack: 1,
},
{
    name : 'Greathelm',
    slot: 'head', 
    dexterity: -1,
    intelligence: 2,
    charisma: 0,
    luck: 0,
    attack: 2,
},
{
    name : 'Jaws',
    slot: 'head', 
    dexterity: 0,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 2,
},
{
    name : 'Mask',
    slot: 'head', 
    dexterity: 0,
    intelligence: 1,
    charisma: 0,
    luck: 0,
    attack: 1,
},
{
    name : 'Defender',
    slot: 'left', 
    dexterity: -2,
    intelligence: 1,
    charisma: 1,
    luck: 0,
    attack: 3,
},
{
    name : 'Deflector',
    slot: 'left', 
    dexterity: 0,
    intelligence: 2,
    charisma: 0,
    luck: 0,
    attack: 2,
},
{
    name : 'Shield',
    slot: 'left', 
    dexterity: 0,
    intelligence: 1,
    charisma: 1,
    luck: 0,
    attack: 1,
},
{
    name : 'Spellbook',
    slot: 'left', 
    dexterity: 2,
    intelligence: 3,
    charisma: 2,
    luck: 2,
    attack: 0,
},
{
    name : 'Tome',
    slot: 'left', 
    dexterity: -2,
    intelligence: 2,
    charisma: 0,
    luck: 2,
    attack: 0,
},
{
    name : 'charismaps',
    slot: 'legs', 
    dexterity: 1,
    intelligence: 1,
    charisma: 1,
    luck: 0,
    attack: 1,
},
{
    name : 'Guards',
    slot: 'legs', 
    dexterity: 0,
    intelligence: 2,
    charisma: 0,
    luck: 0,
    attack: 2,
},
{
    name : 'Leggings',
    slot: 'legs', 
    dexterity: 1,
    intelligence: 0,
    charisma: 0,
    luck: 1,
    attack: 0,
},
{
    name : 'Legplates',
    slot: 'legs', 
    dexterity: 0,
    intelligence: 2,
    charisma: 1,
    luck: 0,
    attack: 2,
},
{
    name : 'Skins',
    slot: 'legs', 
    dexterity: 2,
    intelligence: 1,
    charisma: 0,
    luck: 0,
    attack: 1,
},
{
    name : 'charismain',
    slot: 'neck', 
    dexterity: 1,
    intelligence: 2,
    charisma: 0,
    luck: 1,
    attack: 2,
},
{
    name : 'Collar',
    slot: 'neck', 
    dexterity: 0,
    intelligence: 1,
    charisma: 0,
    luck: 0,
    attack: 1,
},
{
    name : 'Necklace',
    slot: 'neck', 
    dexterity: 2,
    intelligence: 3,
    charisma: 2,
    luck: 2,
    attack: 3,
},
{
    name : 'Axe',
    slot: 'right', 
    dexterity: 0,
    intelligence: 0,
    charisma: -1,
    luck: 0,
    attack: 1,
},
{
    name : 'Dagger',
    slot: 'right', 
    dexterity: 2,
    intelligence: 0,
    charisma: 0,
    luck: 1,
    attack: 2,
},
{
    name : 'Katana',
    slot: 'right', 
    dexterity: 0,
    intelligence: 0,
    charisma: 1,
    luck: 0,
    attack: 2,
},
{
    name : 'Quarterstaff',
    slot: 'right', 
    dexterity: 2,
    intelligence: 2,
    charisma: 0,
    luck: 1,
    attack: 0,
},
{
    name : 'Sword',
    slot: 'right', 
    dexterity: 0,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 2,
},
{
    name : 'Ring',
    slot: 'ring', 
    dexterity: 1,
    intelligence: 2,
    charisma: 1,
    luck: 1,
    attack: 2,
},
{
    name : 'Ringlet',
    slot: 'ring', 
    dexterity: 0,
    intelligence: 1,
    charisma: 1,
    luck: 0,
    attack: 1,
},
{
    name : 'Battacklestaff',
    slot: 'two handed', 
    dexterity: 0,
    intelligence: 5,
    charisma: 3,
    luck: 2,
    attack: 0,
},
{
    name : 'Crossbow',
    slot: 'two handed', 
    dexterity: 3,
    intelligence: 0,
    charisma: 2,
    luck: 2,
    attack: 4,
},
{
    name : 'Greatsword',
    slot: 'two handed', 
    dexterity: 0,
    intelligence: 0,
    charisma: 2,
    luck: 0,
    attack: 4,
},
{
    name : 'Staff',
    slot: 'two handed', 
    dexterity: 1,
    intelligence: 3,
    charisma: 1,
    luck: 1,
    attack: 0,
},
{
    name : 'Warhammer',
    slot: 'two handed', 
    dexterity: -2,
    intelligence: 0,
    charisma: 0,
    luck: 0,
    attack: 5,
},


];


let randomPrefix = Math.floor(Math.random() * prefixes.length);
let randomMaterials = Math.floor(Math.random() * suffixes.length);
let randomEquipment = Math.floor(Math.random() * equipment.length);

let selectedPrefix = prefixes[randomPrefix];
let selectedSuffixes = suffixes[randomMaterials];
let selectedEquipment = equipment[randomEquipment];

let isThe = ' ';

if(selectedSuffixes.the){
    isThe = ' the ';
}

let finishedName = (selectedPrefix.name + ' ' + selectedEquipment.name + ' ' + 'of' + `${isThe}`  + selectedSuffixes.name);
let slot = selectedEquipment.slot;

let rarity = 'normal';

let owned = 0;

const totalAtt = (selectedPrefix.attack + selectedEquipment.attack + selectedSuffixes.attack);
const totalInt = (selectedPrefix.intelligence + selectedEquipment.intelligence + selectedSuffixes. intelligence);
const totalCha = (selectedPrefix.charisma + selectedEquipment.charisma + selectedSuffixes. charisma);
const totalLuck = (selectedPrefix.luck + selectedEquipment.luck + selectedSuffixes. luck);
const totalDex = (selectedPrefix.dexterity + selectedEquipment.dexterity + selectedSuffixes. dexterity);

return <IItem>{
    name: finishedName,
    slot,
    rarity,
    owned,
    stats: {
    attack: totalAtt,
    charisma: totalCha,
    intelligence: totalInt,
    dexterity: totalDex,
    luck: totalLuck,
    }

    }
}
const Item = model<IItem>('Item', ItemSchema);

export { Item, ItemSchema, IItem };


